### ISSUE TITLE
Checkout Module - No Shipping Required Branch

### ISSUE THREAD

**Issue by kellishouts** [AirshipCMS/Checkout-Module#1]
Can you make a branch of the checkout module that doesn't require shipping address for checkout?

This should **NOT** require any API changes.

It can be done in the hacky way like HIC/SFO, where we just hardcode the shipping address of the owner.

I know we wrote documentation for this, though I think i'd like a branch for it.

(this is for jon, so he can play with it for ASCIIColor).

- [x] Question: _Is_ shipping still required for checkout? I think it is, though wondering if we have accounted for digital types of subs/orders yet.

- [x] Make the branch
- [x] Make sure Readme is up to date
- [ ] Build, and put on E2E Alpha so we can test and show jon.

**Comment by fobabett** [comment]
This feature already exists, there's documentation on how to build the module with shipping disabled. It does require a hardcoded address because shipping addresses are still required.

**Comment by fobabett** [comment]
launched the disabled shipping version. Subscription Orders will only skip the shipping if the item does not require shipping. [Pixel Subscription](https://endtoend.airshipcms-alpha.io/example-subscription-collection/view/pixel-subscription) is the only item that has `has_no_shipments` set.
